[ERROR] 2017-05-25 15:54:58,756 | /bench-repo/frappe-bench/apps/frappe/frappe/app.py:
Site: site1.local
Form Dict: {
 "cmd": "mynewapp2.random.myprojects.set_dep", 
 "guide": "INS/00002"
}
Request Error
Traceback (most recent call last):
  File "/bench-repo/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/bench-repo/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/bench-repo/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/bench-repo/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/bench-repo/frappe-bench/apps/mynewapp2/mynewapp2/random/myprojects.py", line 18, in set_dep
    return json.dumps(ins.__dict__)
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 5, 21, 20, 21, 13, 409987) is not JSON serializable
[ERROR] 2017-05-25 15:54:59,028 | /bench-repo/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 15:54:58.759836-127.0.0.1-b24
